version: '3.9'
services:
  mysql:
    platform: linux/amd64
    image: mysql:8.0.26
    restart: always
    environment:
      MYSQL_DATABASE: exams
      MYSQL_USER: thanh
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3305:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080
